
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #  quartz定时任务
  quartz:
    #数据库方式
    job-store-type: jdbc
    scheduler-name: newsScheduler
    #相关属性配置
    properties:
      org:
        quautz:
          scheduler:
            instanceName: AUTO
          jobStroe:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
#   redis
  redis:
    database: 2
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
#    elasticsearch
  data:
    elasticsearch:
      cluster-name: justdoit
      cluster-nodes: 127.0.0.1:9300




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.news.entity



